name: xeus-uv
channels:
- conda-forge
dependencies:
- cxx-compiler
- cmake
- make
- xeus>=5.0,<6.0
- xeus-zmq>=3.0,<4.0
- libuvw
- nlohmann_json=3.11.3
# Test dependencies
- pytest
- jupyter_kernel_test>=0.6,<0.7
